### PR TITLE
Updated plist to include xml

### PR DESCRIPTION
**Pull request by thecodechef**

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
I have no context on this.  Can you point to docs on why this is the expected behaviour?

Please always leave bumping the version number to the maintainers.  This looks like it will need to be a breaking change.

**Comment by thecodechef** [comment]
first off thank you for responding and for creating this repo it really helps me out alot.

second i am currently using this in my workflow with one of my sublime projects and no breakage
the reason this needs to happen is because of when u try to do two doctypes in the same file u end up with both on the same line but they need to be separate lines and this helps with that.

third im sorry for bumping without permission next time ill leave it to y'all

**Comment by ForbesLindesay** [comment]
It would be a breaking change for anyone currently using `doctype plist` in pug since the output for those people would be changing.

Why is the new-line required there? Is this required by a spec somewhere or is it just a stylistic choice?  If it's required by the spec, we can update `pug` to always put newlines between consecutive doctypes.  This may be a reasonable thing to just go ahead and do (cc @TimothyGu thoughts?).  I'd much prefer people stick to the much more composable:

``` pug
doctype xml
doctype plist
```

than have to create lots of variants of `xml + {thing}`.  I'd also like to avoid this breaking change unless there's a strong motivation.

**Comment by thecodechef** [comment]
im good with that but until u implement that feature im sticking with this tho send me a metion when u get that feature locked in the source then i can start using it ok @ForbesLindesay @TimothyGu 

btw thanks again for answering me im still quite new to the programming world.

**Comment by TimothyGu** [comment]
I've just made a new release for doctypes and pug, which means that you can use the feature @ForbesLindesay mentioned right now, if you update to pug＠2.0.0-beta5.

**Pull request closed without merging**
