### PR TITLE
Added PISI Doctype for Solus OS

### PR DESCRIPTION
**Pull request by thecodechef**

### CODE REVIEW

**Comment by thecodechef** [comment]
hey @ForbesLindesay  & @TimothyGu this is a good doctype to add to the list it is for the Linux Distro `Solus OS` and it help alot in there development of the native and 3rd party packages for the system please say yes :+1:

**Comment by TimothyGu** [comment]
Okay, I would have to say that this is pretty niche. Property list is niche enough, but at least it's pretty commonly used in the entire Apple world. On the other hand I've never even heard of Solus OS (or Pardus OS, the source of the PiSi package manager). This repo is designed to be a database of shorthands of common doctypes, not shorthands of _all_ doctypes.

**Comment by thecodechef** [comment]
Ok thank you for ur opinion about it @TimothyGu

**Comment by thecodechef** [comment]
and your missing out on 'Solus OS' it is quite fast on bootup and it is easier to use than any other Distro that i have chosen to try out, you should give it try-out and see if u like it @TimothyGu 

Here is the link to their Homepage
http://www.solus-project.com

**Comment by TimothyGu** [comment]
Nah, I'm good with my Debian GNOME 3 :)

**Comment by thecodechef** [comment]
Lol yeah gnome has it going on @TimothyGu

**Pull request closed without merging**
